
# Site settings
baseurl: ""
url: xegyn.github.io

# Build settings
markdown: kramdown
permalink: pretty

# Frontmatter defaults
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
